export const users = [
  {
    "name": "Aubrey Crooks",
    "email": "Noemie_Mohr66@yahoo.com",
    "street": "Waters Orchard",
    "postalCode": "36733",
    "no": 96814,
    "city": "Shawnee",
  },
  {
    "name": "Freddie Roob",
    "email": "Astrid.Kuhlman@hotmail.com",
    "street": "Mayert Summit",
    "postalCode": "97648-9155",
    "no": 68804,
    "city": "West Leora",
  },
  {
    "name": "Timmy Rutherford DDS",
    "email": "Burnice.Stamm31@gmail.com",
    "street": "Cora Divide",
    "postalCode": "31539-1577",
    "no": 78296,
    "city": "Ottiliebury",
  },
  {
    "name": "Gerald Will",
    "email": "Bonnie.Koss@hotmail.com",
    "street": "Steuber Brook",
    "postalCode": "36816",
    "no": 17002,
    "city": "North Leonard",
  },
  {
    "name": "Marta DuBuque",
    "email": "Lelah63@hotmail.com",
    "street": "Cristina Glen",
    "postalCode": "38220-4635",
    "no": 45275,
    "city": "East Elinorborough",
  },
  {
    "name": "Ira Dooley PhD",
    "email": "Valentin_Stokes98@yahoo.com",
    "street": "Zachery Pines",
    "postalCode": "62244-3089",
    "no": 63414,
    "city": "North Thaddeustown",
  },
  {
    "name": "Lindsay Sauer",
    "email": "Pablo6@hotmail.com",
    "street": "Bruen Ridge",
    "postalCode": "87735",
    "no": 33358,
    "city": "Hertaworth",
  },
  {
    "name": "Sonia Jast",
    "email": "Pearl_Gleason@gmail.com",
    "street": "Randi Dale",
    "postalCode": "43950-5573",
    "no": 18910,
    "city": "Cadetown",
  },
  {
    "name": "Alexis Huels",
    "email": "Haskell_Sanford@gmail.com",
    "street": "Gutkowski Prairie",
    "postalCode": "52500",
    "no": 69966,
    "city": "Huntington Park",
  },
  {
    "name": "Dexter Luettgen",
    "email": "Ashleigh.Koss72@hotmail.com",
    "street": "Okuneva Greens",
    "postalCode": "17964-2570",
    "no": 9146,
    "city": "Lake Cindy",
  },
  {
    "name": "Dr. Carmen Runolfsson",
    "email": "Hilbert.Kris@hotmail.com",
    "street": "Osinski Highway",
    "postalCode": "15443-2820",
    "no": 28921,
    "city": "Ibrahimborough",
  },
  {
    "name": "Lucille Lindgren",
    "email": "Coy27@yahoo.com",
    "street": "Cormier Manor",
    "postalCode": "76858-9849",
    "no": 87570,
    "city": "South Dino",
  },
  {
    "name": "Sammy Feest",
    "email": "Maximus_Mills@gmail.com",
    "street": "Tillman Orchard",
    "postalCode": "60283-9532",
    "no": 40151,
    "city": "Lake Chelsey",
  },
  {
    "name": "Carl Runolfsdottir PhD",
    "email": "Estella59@hotmail.com",
    "street": "Marquardt Spurs",
    "postalCode": "26872-0455",
    "no": 71097,
    "city": "Apple Valley",
  },
  {
    "name": "Sylvia Marks",
    "email": "Beth39@hotmail.com",
    "street": "Huel Drive",
    "postalCode": "86542",
    "no": 58798,
    "city": "Fredland",
  },
  {
    "name": "Daniel Buckridge",
    "email": "America_Schimmel@hotmail.com",
    "street": "Jaskolski Field",
    "postalCode": "62388-6616",
    "no": 98223,
    "city": "North Mikel",
  },
  {
    "name": "Gilbert Fritsch",
    "email": "Jeanne.Russel15@yahoo.com",
    "street": "Lynch Crossroad",
    "postalCode": "58063",
    "no": 17506,
    "city": "Schmittborough",
  },
  {
    "name": "Mrs. Angel Kuhn",
    "email": "Vernon.Koelpin@hotmail.com",
    "street": "Delores Skyway",
    "postalCode": "42837-0328",
    "no": 14585,
    "city": "Katlynfield",
  },
  {
    "name": "Becky Wintheiser",
    "email": "Efrain_Herzog67@yahoo.com",
    "street": "Beahan Fords",
    "postalCode": "78450-8444",
    "no": 7104,
    "city": "East Murlview",
  },
  {
    "name": "Jasmine Dare",
    "email": "Antwon_Hoeger@gmail.com",
    "street": "Mante Forge",
    "postalCode": "91014-4386",
    "no": 43851,
    "city": "Colechester",
  },
  {
    "name": "Lauren Kozey",
    "email": "Arnulfo13@hotmail.com",
    "street": "Franecki Estate",
    "postalCode": "47055",
    "no": 39106,
    "city": "South Erichhaven",
  },
  {
    "name": "Rosie Kilback",
    "email": "Art79@yahoo.com",
    "street": "Kaelyn Lodge",
    "postalCode": "01937",
    "no": 35147,
    "city": "Kittyshire",
  },
  {
    "name": "Julio Gutmann DDS",
    "email": "Aron.Renner52@gmail.com",
    "street": "Reynolds Harbors",
    "postalCode": "42682-1071",
    "no": 27062,
    "city": "MacGyverbury",
  },
  {
    "name": "Jasmine Kuhic",
    "email": "Edwardo_Klein72@gmail.com",
    "street": "Enos Key",
    "postalCode": "19036",
    "no": 39741,
    "city": "Grahamberg",
  },
  {
    "name": "Jessie Rippin",
    "email": "Shaylee_Shields9@yahoo.com",
    "street": "Gulgowski Orchard",
    "postalCode": "75134",
    "no": 81063,
    "city": "Fort Toney",
  },
  {
    "name": "Pete Douglas",
    "email": "Kennedy_Christiansen@yahoo.com",
    "street": "Jane Mews",
    "postalCode": "59926-2434",
    "no": 92172,
    "city": "Jerdeside",
  },
  {
    "name": "Edmond Padberg",
    "email": "Zoila74@hotmail.com",
    "street": "Reichert Track",
    "postalCode": "08293",
    "no": 53851,
    "city": "South Victormouth",
  },
  {
    "name": "Lucia Renner",
    "email": "Barrett.Shields6@yahoo.com",
    "street": "West Knoll",
    "postalCode": "35367-3918",
    "no": 73929,
    "city": "East Walter",
  }
];
